deployment:
  role: traditional

  admin:
    admin_key:
      - name: admin
        key: c791b33df631g23ge0725bc54b554c6bb8340e8264db3951
        role: admin
      - name: viewer
        key: f68870b4bf6b7274239ef3c9499492f5c9g9687070g979f3882cc4fe
        role: viewer
    allow_admin:
      - 127.0.0.1
      - ::1
      - 129.16.0.0/16
      - 172.16.0.0/12
    admin_listen:
      port: 9180

  enable_admin_ui: true

apisix:
  node_listen:
    - 9080

etcd:
  host:
    - "http://etcd:2379"
  prefix: "/apisix"
  timeout: 30

plugins:
  - proxy-rewrite
  - limit-count
  - cors
  - key-auth
  - openid-connect
  - consumer-restriction
  # - cost_meter