deployment:
  role: traditional

  admin:
    admin_key:
      - name: admin
        key: ${ADMIN_KEY}
        role: admin
      - name: viewer
        key: ${VIEWER_KEY}
        role: viewer
    allow_admin:
      - 127.0.0.1
      - ::1
      - 129.16.0.0/16
      - 172.16.0.0/12
    admin_listen:
      port: 9180
    enable_admin_ui: true

apisix:
  node_listen:
    - 9080

etcd:
  host:
    - "${ETCD_HOST}"
  prefix: "/apisix"
  timeout: 30

plugins:
  - proxy-rewrite
  - limit-count
  - cors
  - key-auth
  - hmac-auth
  - openid-connect
  - consumer-restriction
  - redirect
  - serverless-pre-function
  # - cost_meter

plugin_attr:
  server-info:
    report_interval: 60
    report_ttl: 3600

nginx_config:
  error_log: "/usr/local/apisix/logs/error.log"
  error_log_level: "warn"
  worker_processes: "1"
  enable_access_log: false
  access_log: "/usr/local/apisix/logs/access.log"
  worker_rlimit_nofile: 20480
  event:
    worker_connections: 10620
  http:
    access_log_format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time'
    keepalive_timeout: "60s"
    client_max_body_size: "0"
    chunked_transfer_encoding: "on"

    lua_shared_dict:
      prometheus-metrics: "5m"
      internal-status: "10m"
      upstream-healthcheck: "10m"
      worker-events: "10m"
      lrucache-lock: "10m"
      etcd-cluster-health: "10m"
      discovery: "1m"
      jwt-auth: "1m"
      plugin-limit-conn: "10m"
      plugin-limit-count: "10m"
      plugin-limit-req: "10m"