#!/bin/bash
# Learning test: Document OpenAI /v1/models response format
# Usage: OPENAI_API_KEY=sk-xxx ./openai-models.sh

set -euo pipefail
cd "$(dirname "$0")"

: "${OPENAI_API_KEY:?Set OPENAI_API_KEY}"

mkdir -p .outputs
RAW=".outputs/openai-models-response.json"
SCHEMA="openai-models-schema.md"

echo "Fetching OpenAI /v1/models..."
curl -s https://api.openai.com/v1/models \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  > "$RAW"

echo "Generating schema summary..."

cat > "$SCHEMA" << 'EOF'
# OpenAI /v1/models Response Schema

Generated by `./openai-models.sh`

## Top-level structure
EOF

echo '```json' >> "$SCHEMA"
jq '{object, data: "array of model objects"}' "$RAW" >> "$SCHEMA"
echo '```' >> "$SCHEMA"

echo "" >> "$SCHEMA"
echo "## Model object fields" >> "$SCHEMA"
echo '```' >> "$SCHEMA"
jq -r '.data[0] | keys[]' "$RAW" >> "$SCHEMA"
echo '```' >> "$SCHEMA"

echo "" >> "$SCHEMA"
echo "## Sample model (redacted)" >> "$SCHEMA"
echo '```json' >> "$SCHEMA"
jq '.data | map(select(.id | startswith("gpt-4o"))) | .[0]' "$RAW" >> "$SCHEMA"
echo '```' >> "$SCHEMA"

echo "" >> "$SCHEMA"
echo "## Field analysis" >> "$SCHEMA"
echo '```' >> "$SCHEMA"
echo "Total models: $(jq '.data | length' "$RAW")" >> "$SCHEMA"
echo "All have 'created': $(jq '[.data[].created] | all' "$RAW")" >> "$SCHEMA"
echo "All have 'owned_by': $(jq '[.data[].owned_by] | all' "$RAW")" >> "$SCHEMA"
echo '```' >> "$SCHEMA"

echo ""
echo "Done. Raw response: $RAW"
echo "Schema summary: $SCHEMA"
