#!/bin/bash
# Learning test: Compare OpenAI streaming responses
# Direct API vs via ai-proxy (APISIX)
#
# Usage:
#   OPENAI_API_KEY=sk-xxx ./openai-streaming-comparison.sh
#   OPENAI_API_KEY=sk-xxx APISIX_URL=http://localhost:9080 APISIX_KEY=xxx ./openai-streaming-comparison.sh

set -euo pipefail
cd "$(dirname "$0")"

: "${OPENAI_API_KEY:?Set OPENAI_API_KEY}"

APISIX_URL="${APISIX_URL:-}"
APISIX_KEY="${APISIX_KEY:-}"

mkdir -p .outputs

SCHEMA="openai-streaming-schema.md"

echo "=== Test 1: Direct OpenAI, stream_options NOT set ==="
curl -s https://api.openai.com/v1/chat/completions \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "gpt-4o-mini",
    "messages": [{"role": "user", "content": "Say hi"}],
    "stream": true,
    "max_tokens": 10
  }' > .outputs/direct-no-stream-options.txt
echo "Done: .outputs/direct-no-stream-options.txt"

echo ""
echo "=== Test 2: Direct OpenAI, include_usage: true ==="
curl -s https://api.openai.com/v1/chat/completions \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "gpt-4o-mini",
    "messages": [{"role": "user", "content": "Say hi"}],
    "stream": true,
    "max_tokens": 10,
    "stream_options": {"include_usage": true}
  }' > .outputs/direct-include-usage-true.txt
echo "Done: .outputs/direct-include-usage-true.txt"

echo ""
echo "=== Test 3: Direct OpenAI, include_usage: false ==="
curl -s https://api.openai.com/v1/chat/completions \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "gpt-4o-mini",
    "messages": [{"role": "user", "content": "Say hi"}],
    "stream": true,
    "max_tokens": 10,
    "stream_options": {"include_usage": false}
  }' > .outputs/direct-include-usage-false.txt
echo "Done: .outputs/direct-include-usage-false.txt"

# APISIX tests (optional)
if [[ -n "$APISIX_URL" && -n "$APISIX_KEY" ]]; then
  echo ""
  echo "=== Test 4: Via APISIX ai-proxy, stream_options NOT set ==="
  curl -s "$APISIX_URL/ai/v1/chat/completions" \
    -H "Authorization: Bearer $APISIX_KEY" \
    -H "Content-Type: application/json" \
    -d '{
      "model": "gpt-4o-mini",
      "messages": [{"role": "user", "content": "Say hi"}],
      "stream": true,
      "max_tokens": 10
    }' > .outputs/apisix-no-stream-options.txt
  echo "Done: .outputs/apisix-no-stream-options.txt"

  echo ""
  echo "=== Test 5: Via APISIX ai-proxy, include_usage: false (should be overwritten) ==="
  curl -s "$APISIX_URL/ai/v1/chat/completions" \
    -H "Authorization: Bearer $APISIX_KEY" \
    -H "Content-Type: application/json" \
    -d '{
      "model": "gpt-4o-mini",
      "messages": [{"role": "user", "content": "Say hi"}],
      "stream": true,
      "max_tokens": 10,
      "stream_options": {"include_usage": false}
    }' > .outputs/apisix-include-usage-false.txt
  echo "Done: .outputs/apisix-include-usage-false.txt"
else
  echo ""
  echo "Skipping APISIX tests (set APISIX_URL and APISIX_KEY to enable)"
fi

echo ""
echo "=== Generating schema analysis ==="

cat > "$SCHEMA" << 'EOF'
# OpenAI Streaming Response Comparison

Generated by `./openai-streaming-comparison.sh`

## Test Matrix

| Test | stream_options | Expected behavior |
|------|----------------|-------------------|
| 1. Direct, not set | (none) | No usage chunk |
| 2. Direct, true | include_usage: true | Usage chunk at end |
| 3. Direct, false | include_usage: false | No usage chunk |
| 4. APISIX, not set | (none) → forced true | Usage chunk (ai-proxy injects) |
| 5. APISIX, false | include_usage: false → forced true | Usage chunk (ai-proxy overwrites) |

## SSE Chunk Structure

### Content chunk (normal)
EOF

echo '```json' >> "$SCHEMA"
# Extract a content chunk (has choices with delta.content)
grep "^data:" .outputs/direct-include-usage-true.txt | head -2 | tail -1 | sed 's/^data: //' | jq -r '.' 2>/dev/null >> "$SCHEMA" || echo "(parse error)" >> "$SCHEMA"
echo '```' >> "$SCHEMA"

cat >> "$SCHEMA" << 'EOF'

### Usage chunk (when include_usage: true)
EOF

echo '```json' >> "$SCHEMA"
# Extract usage chunk (has usage field, empty choices)
grep "^data:" .outputs/direct-include-usage-true.txt | grep -v "\[DONE\]" | tail -1 | sed 's/^data: //' | jq -r '.' 2>/dev/null >> "$SCHEMA" || echo "(parse error)" >> "$SCHEMA"
echo '```' >> "$SCHEMA"

cat >> "$SCHEMA" << 'EOF'

## Comparison: Has usage chunk?

EOF

echo "| File | Has usage chunk | Chunk count |" >> "$SCHEMA"
echo "|------|-----------------|-------------|" >> "$SCHEMA"

for f in .outputs/direct-*.txt; do
  name=$(basename "$f")
  has_usage="no"
  if grep -q '"usage":\s*{' "$f" 2>/dev/null; then
    has_usage="yes"
  fi
  count=$(grep -c "^data:" "$f" 2>/dev/null || echo "0")
  echo "| $name | $has_usage | $count |" >> "$SCHEMA"
done

if [[ -f .outputs/apisix-no-stream-options.txt ]]; then
  for f in .outputs/apisix-*.txt; do
    name=$(basename "$f")
    has_usage="no"
    if grep -q '"usage":\s*{' "$f" 2>/dev/null; then
      has_usage="yes"
    fi
    count=$(grep -c "^data:" "$f" 2>/dev/null || echo "0")
    echo "| $name | $has_usage | $count |" >> "$SCHEMA"
  done
fi

cat >> "$SCHEMA" << 'EOF'

## Structural Differences

### With include_usage: true
- All content chunks have `"usage": null`
- Final chunk before [DONE] has `"choices": []` and `"usage": {...}`

### Without include_usage (or false)
- Content chunks do NOT have `"usage"` field at all
- No usage chunk at end

## Observed Behavior
EOF

echo "" >> "$SCHEMA"

# Check if usage field present in non-usage chunks
echo "### usage field in content chunks" >> "$SCHEMA"
echo "" >> "$SCHEMA"

if grep "^data:" .outputs/direct-no-stream-options.txt | head -2 | grep -q '"usage"'; then
  echo "- **Direct (no stream_options)**: usage field present (null)" >> "$SCHEMA"
else
  echo "- **Direct (no stream_options)**: usage field ABSENT" >> "$SCHEMA"
fi

if grep "^data:" .outputs/direct-include-usage-true.txt | head -2 | grep -q '"usage"'; then
  echo "- **Direct (include_usage: true)**: usage field present (null)" >> "$SCHEMA"
else
  echo "- **Direct (include_usage: true)**: usage field ABSENT" >> "$SCHEMA"
fi

if grep "^data:" .outputs/direct-include-usage-false.txt | head -2 | grep -q '"usage"'; then
  echo "- **Direct (include_usage: false)**: usage field present (null)" >> "$SCHEMA"
else
  echo "- **Direct (include_usage: false)**: usage field ABSENT" >> "$SCHEMA"
fi

echo ""
echo "Done. Schema: $SCHEMA"
echo ""
echo "To run with APISIX:"
echo "  OPENAI_API_KEY=\$OPENAI_API_KEY APISIX_URL=http://localhost:9080 APISIX_KEY=your-key ./openai-streaming-comparison.sh"
