#!/bin/bash
# Learning test: Compare OpenAI vs Anthropic API protocols
# Usage: OPENAI_API_KEY=sk-xxx ANTHROPIC_API_KEY=sk-ant-xxx ./openai-vs-anthropic-protocol.sh

set -euo pipefail
cd "$(dirname "$0")"

: "${OPENAI_API_KEY:?Set OPENAI_API_KEY}"
: "${ANTHROPIC_API_KEY:?Set ANTHROPIC_API_KEY}"

mkdir -p .outputs

SCHEMA="openai-vs-anthropic-protocol.md"

echo "=== Test 1: OpenAI chat completions (non-streaming) ==="
curl -s https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4o-mini",
    "messages": [
      {"role": "system", "content": "You are helpful."},
      {"role": "user", "content": "Say hi in 5 words"}
    ],
    "max_tokens": 20
  }' > .outputs/openai-chat-response.json
echo "Done: .outputs/openai-chat-response.json"

echo ""
echo "=== Test 2: Anthropic messages (non-streaming) ==="
curl -s https://api.anthropic.com/v1/messages \
  -H "Content-Type: application/json" \
  -H "anthropic-version: 2023-06-01" \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -d '{
    "model": "claude-3-5-haiku-20241022",
    "max_tokens": 20,
    "system": "You are helpful.",
    "messages": [
      {"role": "user", "content": "Say hi in 5 words"}
    ]
  }' > .outputs/anthropic-messages-response.json
echo "Done: .outputs/anthropic-messages-response.json"

echo ""
echo "=== Test 3: OpenAI streaming ==="
curl -s https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4o-mini",
    "messages": [{"role": "user", "content": "Say hi"}],
    "max_tokens": 10,
    "stream": true
  }' > .outputs/openai-chat-streaming.txt
echo "Done: .outputs/openai-chat-streaming.txt"

echo ""
echo "=== Test 4: Anthropic streaming ==="
curl -s https://api.anthropic.com/v1/messages \
  -H "Content-Type: application/json" \
  -H "anthropic-version: 2023-06-01" \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -d '{
    "model": "claude-3-5-haiku-20241022",
    "max_tokens": 10,
    "messages": [{"role": "user", "content": "Say hi"}],
    "stream": true
  }' > .outputs/anthropic-messages-streaming.txt
echo "Done: .outputs/anthropic-messages-streaming.txt"

echo ""
echo "=== Generating protocol comparison ==="

cat > "$SCHEMA" << 'EOF'
# OpenAI vs Anthropic API Protocol Comparison

Generated by `./openai-vs-anthropic-protocol.sh`

## Request Differences

| Aspect | OpenAI `/v1/chat/completions` | Anthropic `/v1/messages` |
|--------|-------------------------------|--------------------------|
| **Auth header** | `Authorization: Bearer <key>` | `x-api-key: <key>` |
| **Version header** | (none) | `anthropic-version: 2023-06-01` |
| **System message** | In messages array `{"role": "system", ...}` | Top-level `"system": "..."` field |
| **Required fields** | model, messages | model, messages, max_tokens |
| **max_tokens** | Optional (has default) | **Required** |

### Request body structure

**OpenAI:**
```json
{
  "model": "gpt-4o-mini",
  "messages": [
    {"role": "system", "content": "..."},
    {"role": "user", "content": "..."}
  ],
  "max_tokens": 100
}
```

**Anthropic:**
```json
{
  "model": "claude-3-5-haiku-20241022",
  "system": "...",
  "messages": [
    {"role": "user", "content": "..."}
  ],
  "max_tokens": 100
}
```

## Response Differences (Non-streaming)

EOF

echo "### OpenAI response structure" >> "$SCHEMA"
echo '```json' >> "$SCHEMA"
jq '.' .outputs/openai-chat-response.json >> "$SCHEMA"
echo '```' >> "$SCHEMA"

echo "" >> "$SCHEMA"
echo "### Anthropic response structure" >> "$SCHEMA"
echo '```json' >> "$SCHEMA"
jq '.' .outputs/anthropic-messages-response.json >> "$SCHEMA"
echo '```' >> "$SCHEMA"

cat >> "$SCHEMA" << 'EOF'

## Key Response Field Mapping

| Concept | OpenAI field | Anthropic field |
|---------|--------------|-----------------|
| Response ID | `id` (chatcmpl-xxx) | `id` (msg_xxx) |
| Object type | `object: "chat.completion"` | `type: "message"` |
| Model used | `model` | `model` |
| Content | `choices[0].message.content` | `content[0].text` |
| Role | `choices[0].message.role` | `role` |
| Finish reason | `choices[0].finish_reason` | `stop_reason` |
| Input tokens | `usage.prompt_tokens` | `usage.input_tokens` |
| Output tokens | `usage.completion_tokens` | `usage.output_tokens` |

## Streaming Differences

### OpenAI SSE format
EOF

echo '```' >> "$SCHEMA"
head -5 .outputs/openai-chat-streaming.txt >> "$SCHEMA"
echo '...' >> "$SCHEMA"
echo '```' >> "$SCHEMA"

cat >> "$SCHEMA" << 'EOF'

### Anthropic SSE format
EOF

echo '```' >> "$SCHEMA"
head -10 .outputs/anthropic-messages-streaming.txt >> "$SCHEMA"
echo '...' >> "$SCHEMA"
echo '```' >> "$SCHEMA"

cat >> "$SCHEMA" << 'EOF'

## Anthropic-specific SSE Events

Anthropic uses typed events:
- `message_start` - Initial message metadata
- `content_block_start` - Start of content block
- `content_block_delta` - Incremental text
- `content_block_stop` - End of content block
- `message_delta` - Final stats (stop_reason, usage)
- `message_stop` - Stream complete

OpenAI uses simpler format:
- `data: {...}` chunks with delta content
- `data: [DONE]` to signal end

## Why Claude Code Needs Native Anthropic Protocol

1. **Different auth mechanism** - x-api-key vs Bearer token
2. **Required anthropic-version header** - No equivalent in OpenAI
3. **System message location** - Top-level field vs messages array
4. **max_tokens required** - Will fail without it
5. **Response structure completely different** - Can't just change base URL
6. **SSE event types** - Different streaming protocol
7. **Anthropic-specific endpoints** - `/v1/messages/count_tokens` has no OpenAI equivalent

## Conclusion

**Claude Code CANNOT work by just changing base URL to an OpenAI-compatible endpoint.**

The protocols are fundamentally different:
- Request format differs (system message, required fields)
- Response format differs (field names, nesting)
- Streaming protocol differs (event types)
- Auth mechanism differs

This is why we need `/provider/anthropic/*` sidecar routes that pass through native Anthropic protocol.
EOF

echo ""
echo "Done. Schema: $SCHEMA"
